<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pagos_Dominio\Pagos_Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Commands\" />
    <Folder Include="Handlers\Commands\" />
    <Folder Include="Handlers\Queries\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Queries\" />
  </ItemGroup>

</Project>
